config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'

  devise_for :users, controllers: {
      registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account_summary.rb
class AccountSummary < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/referral_code.rb
class ReferralCode < ApplicationRecord
  belongs_to :user
  has_many :referral_users, class_name: 'User', foreign_key: 'referral_code_id'

  validates :code, presence: true, uniqueness: true
  before_validation :generate_code, on: :create

  private
  def generate_code
    self.code = SecureRandom.urlsafe_base64(4)
    generate_code if ReferralCode.exists?(code: self.code)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessor :referral_code
  validate :check_referral_code, on: :create, if: 'referral_code.present?'
  after_create :post_processing

  has_one :referral, class_name: 'ReferralCode', foreign_key: 'user_id'
  belongs_to :referral_by_code, class_name: 'ReferralCode', foreign_key: 'referral_code_id', optional: true
  has_many :account_summaries

  def credit_amount amount_to_add, description=nil
    ActiveRecord::Base.transaction do
      update(current_amount_in_cents: self.current_amount_in_cents.to_i + amount_to_add*100)
      account_summaries.create(amount_in_cents: amount_to_add*100, credit: true, desciption: description)
    end
  end

  def account_balance_in_cents
    current_amount_in_cents.to_i
  end

  private

  def check_referral_code
    errors.add(:referral_code, "not valid") unless get_referral_by_code
  end

  def post_processing
    create_referral
    process_referral_code
  end

  def process_referral_code
    # Setting refer_by
    if get_referral_by_code
      self.referral_by_code = get_referral_by_code
      apply_referral_offer if save
    end
  end

  def apply_referral_offer
    get_referral_by_code.user.credit_amount(20, "New user sign-up with user's invitation code #{get_referral_by_code}")
    credit_amount(20, "Sign-up promo with code #{get_referral_by_code.code}")
  end

  def get_referral_by_code
    @referral_by_code ||= ReferralCode.find_by(code: self.referral_code)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :referral_code])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    build_resource({referral_code: params.delete(:referral_code)})
    yield resource if block_given?
    respond_with resource
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Hello there!</h1>
<%= render partial: 'shared/referral_code' %>
<% if current_user.present? && current_user.account_summaries.any? %>
    <br>
    <span>Account summary</span>
    <table class='table table-striped'>
      <thead>
      <tr>
        <th>Amount</th>
        <th>Type</th>
        <th>Date</th>
      </tr>
      </thead>
      <% current_user.account_summaries.each do |account_summary|%>
      <tr>
        <td><%= number_to_currency(account_summary.amount_in_cents.to_i / 100, :unit => "$") %></td>
        <td><%= account_summary.credit ? 'Credited' : 'Debited' %></td>
        <td><%= account_summary.created_at.to_date %></td>
      </tr>
      <% end %>
    </table>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
<% end %>

app/views/layouts/_head.html.erb
<head>
  <title>Newgadgets</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<span>
  <%= link_to 'home', home_index_path%>
</span>

<span class="navbar-text pull-right">
  <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      Current account balance <%= number_to_currency(current_user.account_balance_in_cents / 100, :unit => "$") %>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
      <%= link_to 'Sign up', new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to 'Login', new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render partial: 'layouts/head' %>
  <body>
    <div class="col-md-10 col-md-offset-1">
      <%= render partial: 'layouts/header' %>
      <%= render partial: 'layouts/flash'%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_referral_code.html.erb
<% if current_user.present? %>
    Share this referral code with your friends and you will be credited $20 when they sign-up with your referral code
    <br>
      <%= text_field_tag 'referral_link', new_user_registration_url(:referral_code => current_user.referral.code), readonly: true, class: 'form-control'%>
    <br> or share on social media
    <%= social_share_button_tag('Sign-up and get $20 bonus', :url => new_user_registration_url(:referral_code => current_user.referral.code)) %>
<% end %>